# HackAI Comprehensive Security and Compliance Configuration
# Enterprise-grade security settings for all environments

# Global Security Settings
global:
  security_level: high
  environment: production
  encryption_enabled: true
  audit_enabled: true
  monitoring_enabled: true
  compliance_enabled: true
  incident_response_enabled: true
  threat_detection_enabled: true

# Authentication Configuration
authentication:
  multi_factor_enabled: true
  password_policy:
    min_length: 12
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special_chars: true
    max_age_days: 90
    history_count: 12
    lockout_attempts: 5
    lockout_duration: 30m
  session_timeout: 8h
  max_login_attempts: 3
  lockout_duration: 15m
  token_expiration: 1h
  refresh_token_enabled: true
  refresh_token_expiration: 24h
  biometric_enabled: false
  sso:
    enabled: true
    providers:
      - name: "azure_ad"
        client_id: "${AZURE_AD_CLIENT_ID}"
        client_secret: "${AZURE_AD_CLIENT_SECRET}"
        tenant_id: "${AZURE_AD_TENANT_ID}"
      - name: "okta"
        client_id: "${OKTA_CLIENT_ID}"
        client_secret: "${OKTA_CLIENT_SECRET}"
        domain: "${OKTA_DOMAIN}"
  oauth:
    enabled: true
    providers:
      - name: "github"
        client_id: "${GITHUB_CLIENT_ID}"
        client_secret: "${GITHUB_CLIENT_SECRET}"
      - name: "google"
        client_id: "${GOOGLE_CLIENT_ID}"
        client_secret: "${GOOGLE_CLIENT_SECRET}"

# Authorization Configuration
authorization:
  rbac_enabled: true
  abac_enabled: true
  default_role: "user"
  permission_caching: true
  cache_expiration: 15m
  policy_evaluation:
    engine: "opa"
    timeout: 5s
    cache_enabled: true
  resource_hierarchy:
    enabled: true
    max_depth: 10
  dynamic_permissions: true
  roles:
    - name: "admin"
      permissions: ["*"]
      description: "Full system access"
    - name: "security_analyst"
      permissions: 
        - "security:read"
        - "security:analyze"
        - "incidents:manage"
        - "threats:investigate"
      description: "Security analysis and incident response"
    - name: "compliance_officer"
      permissions:
        - "compliance:read"
        - "compliance:audit"
        - "reports:generate"
        - "policies:manage"
      description: "Compliance monitoring and reporting"
    - name: "user"
      permissions:
        - "profile:read"
        - "profile:update"
        - "scans:create"
        - "scans:read"
      description: "Standard user access"

# Encryption Configuration
encryption:
  algorithm: "AES-256-GCM"
  key_size: 256
  key_rotation_interval: 30d
  encryption_at_rest: true
  encryption_in_transit: true
  hsm_enabled: false
  key_management:
    provider: "vault"
    vault_address: "${VAULT_ADDRESS}"
    vault_token: "${VAULT_TOKEN}"
    key_path: "secret/hackai/encryption"
  certificate_management:
    auto_renewal: true
    renewal_threshold: 30d
    ca_provider: "letsencrypt"
    cert_storage: "vault"

# Audit Configuration
audit:
  enabled: true
  log_level: "info"
  retention_days: 365
  storage_type: "elasticsearch"
  elasticsearch:
    hosts: ["${ELASTICSEARCH_HOST}"]
    index_pattern: "hackai-audit-%{+YYYY.MM.dd}"
    username: "${ELASTICSEARCH_USERNAME}"
    password: "${ELASTICSEARCH_PASSWORD}"
  events:
    - "authentication"
    - "authorization"
    - "data_access"
    - "configuration_change"
    - "security_event"
    - "compliance_check"
    - "incident_response"
  sensitive_data_masking: true
  real_time_monitoring: true
  alerting:
    enabled: true
    channels: ["slack", "email", "webhook"]
    rules:
      - name: "failed_login_attempts"
        condition: "failed_logins > 10 in 5m"
        severity: "high"
      - name: "privilege_escalation"
        condition: "role_change to admin"
        severity: "critical"

# Threat Detection Configuration
threat_detection:
  enabled: true
  real_time_analysis: true
  machine_learning_enabled: true
  threat_intelligence:
    enabled: true
    feeds:
      - name: "mitre_attack"
        url: "https://attack.mitre.org/data/enterprise-attack.json"
        update_frequency: "24h"
      - name: "cisa_known_exploited"
        url: "https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json"
        update_frequency: "6h"
      - name: "nvd_cve"
        url: "https://services.nvd.nist.gov/rest/json/cves/2.0"
        update_frequency: "1h"
  indicators:
    - type: "ip_address"
      sources: ["threat_feeds", "honeypots", "security_logs"]
    - type: "domain"
      sources: ["dns_logs", "threat_feeds"]
    - type: "file_hash"
      sources: ["malware_analysis", "threat_feeds"]
    - type: "user_behavior"
      sources: ["authentication_logs", "access_logs"]
  detection_rules:
    - name: "brute_force_attack"
      pattern: "failed_login_attempts > 20 in 1m from same_ip"
      severity: "high"
      response: "block_ip"
    - name: "privilege_escalation"
      pattern: "sudo_usage by non_admin_user"
      severity: "critical"
      response: "alert_security_team"
    - name: "data_exfiltration"
      pattern: "large_data_transfer outside_business_hours"
      severity: "high"
      response: "quarantine_user"

# Compliance Configuration
compliance:
  frameworks:
    soc2:
      enabled: true
      version: "2017"
      scope: ["security", "availability", "confidentiality"]
      assessment_frequency: 90d
      reporting_frequency: 30d
      auto_remediation: true
      controls:
        - id: "CC6.1"
          name: "Logical Access Controls"
          description: "Restrict logical access to system resources"
          implementation: "rbac"
          testing_frequency: 30d
        - id: "CC6.2"
          name: "Authentication"
          description: "Authenticate users before granting access"
          implementation: "multi_factor_auth"
          testing_frequency: 30d
        - id: "CC6.3"
          name: "Authorization"
          description: "Authorize user access to system resources"
          implementation: "abac"
          testing_frequency: 30d
    iso27001:
      enabled: true
      version: "2013"
      scope: ["information_security_management"]
      assessment_frequency: 180d
      reporting_frequency: 90d
      auto_remediation: false
      controls:
        - id: "A.9.1.1"
          name: "Access Control Policy"
          description: "Establish access control policy"
          implementation: "policy_engine"
          testing_frequency: 90d
        - id: "A.12.6.1"
          name: "Management of Technical Vulnerabilities"
          description: "Manage technical vulnerabilities"
          implementation: "vulnerability_scanner"
          testing_frequency: 30d
    gdpr:
      enabled: true
      version: "2018"
      scope: ["data_protection", "privacy"]
      assessment_frequency: 90d
      reporting_frequency: 30d
      auto_remediation: true
      controls:
        - id: "Art.25"
          name: "Data Protection by Design"
          description: "Implement data protection by design"
          implementation: "privacy_controls"
          testing_frequency: 30d
        - id: "Art.32"
          name: "Security of Processing"
          description: "Implement appropriate security measures"
          implementation: "encryption"
          testing_frequency: 30d
    hipaa:
      enabled: false
      version: "2013"
      scope: ["healthcare_data"]
      assessment_frequency: 180d
      reporting_frequency: 90d
      auto_remediation: false
    pci_dss:
      enabled: false
      version: "4.0"
      scope: ["payment_data"]
      assessment_frequency: 365d
      reporting_frequency: 90d
      auto_remediation: false

# Incident Response Configuration
incident_response:
  enabled: true
  auto_response: true
  escalation_enabled: true
  notification_channels: ["slack", "email", "sms", "webhook"]
  response_teams:
    - name: "security_team"
      members: ["security@hackai.dev"]
      escalation_time: 15m
    - name: "management_team"
      members: ["management@hackai.dev"]
      escalation_time: 1h
  playbooks:
    - name: "data_breach"
      triggers: ["data_exfiltration", "unauthorized_access"]
      steps:
        - "isolate_affected_systems"
        - "notify_security_team"
        - "collect_evidence"
        - "assess_impact"
        - "notify_stakeholders"
        - "remediate_vulnerability"
        - "document_incident"
    - name: "malware_detection"
      triggers: ["malware_found", "suspicious_file"]
      steps:
        - "quarantine_system"
        - "analyze_malware"
        - "update_signatures"
        - "scan_network"
        - "remediate_infection"
  severity_levels:
    - name: "critical"
      response_time: 15m
      escalation_time: 30m
      notification: "immediate"
    - name: "high"
      response_time: 1h
      escalation_time: 2h
      notification: "urgent"
    - name: "medium"
      response_time: 4h
      escalation_time: 8h
      notification: "normal"
    - name: "low"
      response_time: 24h
      escalation_time: 48h
      notification: "scheduled"

# Vulnerability Management Configuration
vulnerability_management:
  enabled: true
  scanning_frequency: 24h
  auto_remediation: true
  risk_scoring: "cvss_v3"
  scanners:
    - name: "trivy"
      type: "container"
      enabled: true
      config:
        severity_threshold: "medium"
        ignore_unfixed: false
    - name: "grype"
      type: "container"
      enabled: true
      config:
        fail_on_severity: "high"
    - name: "nuclei"
      type: "web"
      enabled: true
      config:
        templates: ["cves", "vulnerabilities", "misconfigurations"]
  remediation:
    auto_patch: true
    patch_window: "maintenance"
    rollback_enabled: true
    testing_required: true
  reporting:
    frequency: "weekly"
    recipients: ["security@hackai.dev", "devops@hackai.dev"]
    format: ["html", "json", "pdf"]

# Security Monitoring Configuration
monitoring:
  enabled: true
  real_time: true
  metrics_collection: true
  log_aggregation: true
  alerting: true
  dashboards: true
  retention_period: 90d
  storage:
    metrics: "prometheus"
    logs: "elasticsearch"
    traces: "jaeger"
  alerts:
    - name: "high_cpu_usage"
      condition: "cpu_usage > 90% for 5m"
      severity: "warning"
    - name: "memory_exhaustion"
      condition: "memory_usage > 95% for 2m"
      severity: "critical"
    - name: "disk_space_low"
      condition: "disk_usage > 85%"
      severity: "warning"
    - name: "security_event_spike"
      condition: "security_events > 100 in 1m"
      severity: "high"

# Network Security Configuration
network_security:
  firewall_enabled: true
  intrusion_detection: true
  intrusion_prevention: true
  ddos_protection: true
  ssl_inspection: true
  dns_filtering: true
  network_segmentation: true
  zero_trust: true
  policies:
    - name: "default_deny"
      action: "deny"
      priority: 1000
      description: "Deny all traffic by default"
    - name: "allow_https"
      action: "allow"
      protocol: "tcp"
      port: 443
      priority: 100
    - name: "allow_http"
      action: "allow"
      protocol: "tcp"
      port: 80
      priority: 200
    - name: "allow_ssh"
      action: "allow"
      protocol: "tcp"
      port: 22
      source: "management_network"
      priority: 300

# Data Protection Configuration
data_protection:
  classification_enabled: true
  dlp_enabled: true
  encryption_required: true
  backup_encryption: true
  data_masking: true
  retention_policies: true
  classification_levels:
    - name: "public"
      encryption: false
      access_control: "none"
      retention: "7y"
    - name: "internal"
      encryption: true
      access_control: "rbac"
      retention: "5y"
    - name: "confidential"
      encryption: true
      access_control: "abac"
      retention: "3y"
    - name: "restricted"
      encryption: true
      access_control: "strict"
      retention: "1y"
  dlp_rules:
    - name: "credit_card_numbers"
      pattern: "\\b(?:\\d{4}[-\\s]?){3}\\d{4}\\b"
      action: "block"
    - name: "social_security_numbers"
      pattern: "\\b\\d{3}-\\d{2}-\\d{4}\\b"
      action: "alert"
    - name: "email_addresses"
      pattern: "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b"
      action: "monitor"

# Security Automation Configuration
automation:
  enabled: true
  orchestration: true
  playbooks: true
  workflows: true
  auto_response: true
  machine_learning: true
  threat_hunting: true
  continuous_monitoring: true
  integration:
    siem: true
    soar: true
    ticketing: true
    notification: true
  response_actions:
    - name: "block_ip"
      type: "network"
      automation: true
      approval_required: false
    - name: "quarantine_user"
      type: "identity"
      automation: true
      approval_required: true
    - name: "isolate_system"
      type: "endpoint"
      automation: false
      approval_required: true
