version: "1.0.0"
environment: "production"
updated_at: "2024-01-01T00:00:00Z"

# Agentic Security Framework Configuration
agentic_framework:
  enabled: true
  real_time_analysis: true
  threat_response_threshold: 0.7
  auto_block_enabled: true
  learning_mode: true
  max_concurrent_analysis: 20
  threat_retention_duration: "24h"
  alert_cooldown_period: "5m"
  confidence_threshold: 0.8

# AI Firewall Configuration
ai_firewall:
  enabled: true
  ml_detection: true
  behavior_analysis: true
  anomaly_detection: true
  geo_blocking: true
  rate_limiting: true
  block_threshold: 0.7
  alert_threshold: 0.5
  rules:
    - id: "sql_injection_basic"
      name: "Basic SQL Injection Detection"
      enabled: true
      priority: 100
      pattern: "(?i)(union|select|insert|update|delete|drop)\\s+"
      action: "block"
      severity: "high"
      confidence: 0.8
      description: "Detects basic SQL injection patterns"
    - id: "advanced_sql_injection"
      name: "Advanced SQL Injection Detection"
      enabled: true
      priority: 90
      pattern: "(?i)(union\\s+select|or\\s+1\\s*=\\s*1|and\\s+1\\s*=\\s*1|'.*or.*'.*=.*')"
      action: "block"
      severity: "critical"
      confidence: 0.9
      description: "Detects advanced SQL injection patterns"
    - id: "xss_detection"
      name: "XSS Detection"
      enabled: true
      priority: 95
      pattern: "(?i)<script[^>]*>"
      action: "block"
      severity: "high"
      confidence: 0.8
      description: "Detects XSS patterns"
  whitelisted_ips: []
  blacklisted_ips: []
  geo_blocked_countries:
    - "CN"
    - "RU"
    - "KP"

# Input/Output Filter Configuration
input_output_filter:
  enabled: true
  input_validation: true
  output_sanitization: true
  content_analysis: true
  threat_scanning: true
  strict_mode: true
  max_input_length: 100000
  max_output_length: 1000000
  allowed_file_types:
    - "txt"
    - "json"
    - "xml"
    - "csv"
  blocked_patterns:
    - "(?i)(union|select|insert|update|delete|drop)\\s+"
    - "(?i)<script[^>]*>"
    - "(?i)javascript:"
    - "(?i)on\\w+\\s*="
    - "(?i)data:"
    - "(?i)file://"
    - "(?i)eval\\s*\\("
    - "(?i)exec\\s*\\("
  sanitization_level: "strict"
  log_violations: true
  block_on_violation: true
  encoding_detection: true
  malware_scanning: true

# Prompt Guard Configuration
prompt_guard:
  enabled: true
  semantic_analysis: true
  context_analysis: true
  strict_mode: true
  confidence_threshold: 0.7
  max_prompt_length: 10000
  enable_learning: true
  block_suspicious_prompts: true
  log_all_attempts: true
  role_manipulation_detection: true
  instruction_injection_detection: true

# Threat Intelligence Configuration
threat_intelligence:
  enabled: true
  update_interval: "1h"
  sources:
    - "virustotal"
    - "alienvault"
    - "malwaredomainlist"
  api_keys: {}
  cache_timeout: "4h"
  max_cache_size: 10000
  ioc_types:
    - "ip"
    - "domain"
    - "hash"
    - "url"
  reputation_scoring: true
  auto_blocking: true

# Web Layer Configuration
web_layer:
  enabled: true
  security_headers: true
  csp:
    enabled: true
    policy: "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:"
    report_only: false
    report_uri: "/csp-report"
    upgrade_insecure_requests: true
  hsts:
    enabled: true
    max_age: 31536000           # 1 year
    include_subdomains: true
    preload: true
  x_frame_options: "DENY"
  max_request_size: 10485760    # 10MB
  request_timeout: "30s"
  rate_limiting: true
  session_security: true
  cookie_security: true
  ip_filtering: true
  geo_blocking: true

# Authentication Configuration
authentication:
  password_policy:
    min_length: 12
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special: true
    history_count: 10
    max_age: "2160h"            # 90 days
    min_age: "24h"
    complexity_score: 80
  multi_factor_auth:
    enabled: true
    required: true
    methods:
      - "totp"
      - "sms"
      - "email"
    totp_issuer: "HackAI"
    totp_digits: 6
    totp_period: 30
    backup_codes: true
    sms_provider: "twilio"
    email_provider: "sendgrid"
  session_management:
    timeout: "8h"
    max_concurrent_sessions: 3
    secure_cookies: true
    http_only_cookies: true
    same_site_cookies: "Strict"
    session_rotation: true
    idle_timeout: "30m"
  account_lockout:
    enabled: true
    max_failed_attempts: 5
    lockout_duration: "15m"
    reset_on_success: true
    notify_on_lockout: true

# Authorization Configuration
authorization:
  rbac:
    enabled: true
    default_role: "user"
    roles:
      admin: "full_access"
      user: "limited_access"
      readonly: "read_only"
    inheritance: true
  abac:
    enabled: false
    policies: []
    attributes: {}
  permissions:
    granular: true
    resources:
      - "users"
      - "configs"
      - "logs"
      - "metrics"
    actions:
      - "read"
      - "write"
      - "delete"
      - "admin"
    inheritance: true

# Encryption Configuration
encryption:
  data_at_rest:
    enabled: true
    algorithm: "AES-256"
    key_size: 256
    mode: "GCM"
  data_in_transit:
    tls_version: "1.3"
    cipher_suites:
      - "TLS_AES_256_GCM_SHA384"
      - "TLS_CHACHA20_POLY1305_SHA256"
    hsts: true
    cert_pinning: true
  key_management:
    provider: "vault"
    rotation_interval: "2160h"   # 90 days
    backup_enabled: true
    hsm_enabled: false

# Compliance Configuration
compliance:
  gdpr:
    enabled: false
    data_retention: "0s"
    consent_required: false
    right_to_erasure: false
  hipaa:
    enabled: false
    phi_protection: false
    audit_logging: false
    encryption: false
  sox:
    enabled: false
    audit_trails: false
    data_integrity: false
  pci:
    enabled: false
    data_protection: false
    network_security: false
  auditing:
    enabled: true
    log_level: "info"
    retention_period: "2160h"    # 90 days
    destinations:
      - "file"
      - "syslog"

# Monitoring Configuration
monitoring:
  enabled: true
  metrics_enabled: true
  tracing_enabled: true
  health_checks: true
  dashboards: true
  exporters:
    - "prometheus"
    - "jaeger"
  sample_rate: 1.0
  retention_period: "720h"      # 30 days
  endpoints:
    prometheus: "http://prometheus:9090"
    jaeger: "http://jaeger:14268"

# Alerting Configuration
alerting:
  enabled: true
  channels:
    - type: "slack"
      enabled: true
      config:
        webhook_url: ""
      severity:
        - "critical"
        - "high"
    - type: "email"
      enabled: true
      config:
        smtp_server: ""
        recipients: ""
      severity:
        - "critical"
        - "high"
        - "medium"
  rules:
    - id: "high_threat_score"
      name: "High Threat Score Alert"
      enabled: true
      condition: "threat_score > threshold"
      threshold: 0.8
      severity: "critical"
      description: "Alert when threat score exceeds 0.8"
    - id: "multiple_failed_logins"
      name: "Multiple Failed Login Attempts"
      enabled: true
      condition: "failed_logins > threshold"
      threshold: 5
      severity: "high"
      description: "Alert when multiple failed login attempts detected"
  escalation:
    enabled: true
    levels:
      - level: 1
        delay: "5m"
        channels:
          - "slack"
      - level: 2
        delay: "15m"
        channels:
          - "email"
  suppression:
    enabled: true
    duration: "1h"
    rules: []
    whitelist: []

# Logging Configuration
logging:
  level: "info"
  format: "json"
  output:
    - "file"
    - "syslog"
  security_events: true
  audit_logs: true
  retention_period: "2160h"     # 90 days
  encryption: true
  compression: true

# Feature Toggles Configuration
feature_toggles:
  security_features:
    advanced_threat_detection: true
    ml_based_analysis: true
    real_time_blocking: true
  experimental_features:
    ai_powered_rules: false
    behavioral_analysis: true
    predictive_blocking: false
  maintenance_mode: false
  debug_mode: false

# Environment-specific Overrides
overrides: {}
