# LLM Security Proxy - Development Environment Configuration
# Optimized for local development with relaxed security and enhanced debugging

# Server Configuration - Development friendly
server:
  port: 8080
  host: "localhost"
  read_timeout: "60s"  # Longer timeouts for debugging
  write_timeout: "60s"
  idle_timeout: "120s"
  shutdown_timeout: "10s"
  tls_enabled: false
  cors:
    enabled: true
    allowed_origins: ["http://localhost:3000", "http://localhost:8080", "http://127.0.0.1:3000"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
    allowed_headers: ["*"]
    max_age: 86400
  rate_limit:
    enabled: true
    requests_per_minute: 10000  # High limits for development
    burst_size: 1000

# Database Configuration - Local PostgreSQL
database:
  host: "${DB_HOST:-localhost}"
  port: "${DB_PORT:-5432}"
  name: "${DB_NAME:-hackai_dev}"
  user: "${DB_USER:-postgres}"
  password: "${DB_PASSWORD:-}"  # Use environment variable, empty default for local dev
  ssl_mode: "${DB_SSL_MODE:-disable}"
  max_open_conns: 10  # Lower for development
  max_idle_conns: 2
  conn_max_lifetime: "10m"
  conn_max_idle_time: "5m"
  migration_path: "./migrations"
  auto_migrate: true

# Redis Configuration - Local Redis
redis:
  host: "${REDIS_HOST:-localhost}"
  port: "${REDIS_PORT:-6379}"
  password: "${REDIS_PASSWORD:-}"  # Empty default for local dev
  db: "${REDIS_DB:-1}"  # Use different DB for development
  pool_size: 5
  min_idle_conns: 1
  dial_timeout: "10s"
  read_timeout: "5s"
  write_timeout: "5s"
  pool_timeout: "10s"
  idle_timeout: "10m"

# JWT Configuration - Development keys
jwt:
  secret: "${JWT_SECRET:-dev-secret-key-not-for-production}"  # Use env var or dev default
  issuer: "${JWT_ISSUER:-hackai-dev}"
  audience: "${JWT_AUDIENCE:-hackai-dev-users}"
  access_token_duration: "1h"  # Longer for development convenience
  refresh_token_duration: "7d"
  algorithm: "HS256"

# Security Configuration - Relaxed for development
security:
  enabled: true
  strict_mode: false
  default_threat_score: 0.0
  block_high_threat_score: false  # Don't block in development
  threat_score_threshold: 0.9  # Higher threshold
  
  policy_engine:
    enabled: true
    default_action: "allow"
    evaluation_timeout: "10s"  # Longer timeout for debugging
    cache_enabled: false  # Disable caching for development
    cache_ttl: "1m"
    max_policy_size: "10MB"
    
  content_filter:
    enabled: true
    max_content_length: 1000000  # Larger for testing
    scan_timeout: "30s"
    block_malicious_content: false  # Don't block in development
    block_pii: false
    block_toxic_content: false
    toxicity_threshold: 0.9
    
  rate_limiter:
    enabled: true
    strict_mode: false
    global_requests_per_minute: 100000  # Very high limits
    global_requests_per_hour: 1000000
    global_tokens_per_minute: 10000000
    global_tokens_per_hour: 100000000
    user_requests_per_minute: 1000
    user_requests_per_hour: 10000
    user_requests_per_day: 100000
    user_tokens_per_minute: 100000
    user_tokens_per_hour: 1000000
    user_tokens_per_day: 10000000
    user_cost_per_hour: 1000.0
    user_cost_per_day: 5000.0
    user_cost_per_month: 50000.0
    allow_burst: true
    burst_multiplier: 5.0
    burst_window_seconds: 300

# Audit Configuration - Comprehensive logging for development
audit:
  enabled: true
  
  logger:
    enabled: true
    batch_size: 10  # Smaller batches for immediate feedback
    flush_interval: "5s"  # Frequent flushing
    max_queue_size: 1000
    include_request_body: true
    include_response_body: true
    mask_sensitive_data: false  # Don't mask in development
    compress_large_payloads: false
    max_payload_size: "10MB"
    retention_days: 7  # Shorter retention
    
  middleware:
    enabled: true
    log_successful_requests: true
    log_failed_requests: true
    log_blocked_requests: true
    log_security_violations: true
    log_policy_decisions: true
    excluded_endpoints: []  # Log everything in development
    excluded_providers: []
    min_threat_score_to_log: 0.0
    sample_rate: 1.0
    
  service:
    enabled: true
    retention_period: "7d"
    cleanup_interval: "1h"
    archive_old_logs: false
    archive_threshold: "1d"
    enable_metrics: true
    metrics_update_interval: "1m"
    enable_alerts: false  # No alerts in development

# Observability Configuration - Enhanced for development
observability:
  logging:
    level: "debug"  # Verbose logging
    format: "text"  # Human-readable format
    output: "stdout"
    file_path: ""
    add_source: true
    time_format: "RFC3339"
    
  metrics:
    enabled: true
    port: 9090
    path: "/metrics"
    namespace: "hackai_dev"
    subsystem: "llm_security_proxy"
    
  tracing:
    enabled: true  # Enable tracing for development
    service_name: "llm-security-proxy-dev"
    endpoint: "http://localhost:14268/api/traces"  # Local Jaeger
    sample_rate: 1.0  # Trace everything
    insecure: true
    headers: {}

# AI Provider Configuration - Development settings
ai:
  providers:
    openai:
      enabled: true
      api_key: "${OPENAI_API_KEY}"  # Use environment variable
      base_url: "https://api.openai.com/v1"
      timeout: "60s"
      max_retries: 1  # Fewer retries for faster feedback
      models:
        - "gpt-3.5-turbo"
        - "gpt-4"
    anthropic:
      enabled: false
      api_key: "${ANTHROPIC_API_KEY}"
      base_url: "https://api.anthropic.com"
      timeout: "60s"
      max_retries: 1
      models:
        - "claude-3-sonnet"
    azure:
      enabled: false
      
  defaults:
    max_tokens: 1000  # Smaller for cost control
    temperature: 0.7
    top_p: 1.0
    frequency_penalty: 0.0
    presence_penalty: 0.0
    timeout: "60s"
    
  cost_tracking:
    enabled: true
    currency: "USD"
    alert_threshold: 10.0  # Low threshold for development
    daily_limit: 50.0
    monthly_limit: 500.0

# Feature Flags - All features enabled for testing
features:
  enable_real_time_dashboard: true
  enable_policy_testing: true
  enable_threat_simulation: true
  enable_advanced_analytics: true
  enable_export_functionality: true
  enable_webhook_notifications: true
  enable_slack_integration: false
  enable_email_alerts: false

# Notifications - Disabled for development
notifications:
  email:
    enabled: false
  slack:
    enabled: false
  webhook:
    enabled: false

# Development/Debug Configuration - Fully enabled
debug:
  enabled: true
  pprof_enabled: true
  pprof_port: 6060
  verbose_logging: true
  log_sql_queries: true
  disable_auth: false  # Keep auth enabled for testing
  mock_providers: false

# Development-specific settings
development:
  auto_reload: true
  hot_reload_templates: true
  disable_csrf: true
  enable_debug_endpoints: true
  mock_external_services: false
  seed_test_data: true
  reset_db_on_start: false
