apiVersion: v2
name: hackai
description: A comprehensive cybersecurity education and AI-powered security platform
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://hackai.com
sources:
  - https://github.com/hackai/platform
maintainers:
  - name: HackAI Team
    email: team@hackai.com
    url: https://hackai.com
keywords:
  - cybersecurity
  - education
  - ai
  - security
  - vulnerability-scanner
  - threat-intelligence
annotations:
  category: Security
  licenses: MIT
dependencies:
  - name: postgresql
    version: "12.8.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.11.7"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: prometheus
    version: "23.1.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "6.58.7"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled
  - name: jaeger
    version: "0.71.2"
    repository: "https://jaegertracing.github.io/helm-charts"
    condition: monitoring.jaeger.enabled
