project_name: hackai
environment: production
aws:
    enabled: true
    region: us-west-2
    profile: default
    eks:
        cluster_name: hackai-production-eks
        version: "1.28"
        node_groups:
            - name: general
              instance_type: m5.large
              min_size: 2
              max_size: 10
              desired_size: 3
              labels:
                node-type: general
        enable_logging: true
    rds:
        instance_class: db.t3.medium
        engine: postgres
        version: "15.4"
        multi_az: true
    elasticache:
        node_type: cache.t3.micro
        num_nodes: 2
gcp:
    enabled: true
    project_id: hackai-production
    region: us-central1
    zone: us-central1-a
    gke:
        cluster_name: hackai-production-gke
        version: "1.28"
        node_pools:
            - name: general
              machine_type: e2-standard-4
              min_count: 2
              max_count: 10
              initial_count: 3
              labels:
                node-type: general
        enable_autopilot: false
    cloud_sql:
        tier: db-standard-2
        version: POSTGRES_15
        high_availability: true
azure:
    enabled: true
    subscription_id: your-azure-subscription-id
    location: East US
    aks:
        cluster_name: hackai-production-aks
        version: "1.28"
        node_pools:
            - name: general
              machine_type: Standard_D4s_v3
              min_count: 2
              max_count: 10
              initial_count: 3
              labels:
                node-type: general
    postgresql:
        sku: Standard_D4s_v3
        version: "15"
        high_availability: true
monitoring:
    enabled: true
    prometheus: true
    grafana: true
    jaeger: true
    loki: true
    alert_manager: true
security:
    enable_pod_security_policy: true
    enable_network_policy: true
    enable_rbac: true
    enable_opa: true
networking:
    enable_service_mesh: true
    service_mesh_type: istio
    enable_ingress: true
    ingress_class: nginx
